# Etapa 1: imagem base
FROM node:22-alpine

# Etapa 2: diretório de trabalho
WORKDIR /app

# Etapa 3: instala dependências
COPY package*.json ./
RUN npm install

# Etapa 4: copia restante dos arquivos
COPY . .

RUN npm run build

# Etapa 5: roda o Vite em modo desenvolvimento
EXPOSE 5173
CMD ["npm", "run", "dev", "--", "--host"]
