version: '3.9'
services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: perguntados
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis
    restart: always
    ports:
      - '6379:6379'

  backend:
    build: ./backend
    container_name: backend
    restart: always
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: postgres://user:password@postgres:5432/perguntados
      REDIS_URL: redis://redis:6379
    depends_on:
      - postgres
      - redis

  frontend:
    build: ./frontend
    container_name: frontend
    restart: always
    ports:
      - '5173:5173'
    depends_on:
      - backend

volumes:
  pgdata:
